---
# Customization for: https://github.com/geerlingguy/mac-dev-playbook
# Populate roles: ansible-galaxy install -r requirements.yml
downloads: ~/.ansible-downloads/

configure_dotfiles: no
configure_sudoers: yes
configure_terminal: no
configure_osx: yes

dotfiles_repo: https://github.com/Jamyn/mac-dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Dropbox/Development/GitHub/dotfiles
dotfiles_files:
  - .bash_profile
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - awscli
  - autoconf
  - bash-completion
  - doxygen
  - gettext
  - git
  - go
  - gpg
  - hub
  - httpie
  - iperf
  - libevent
  - powerlevel9k
  - sqlite
  - mcrypt
  - nmap
  - node
  - nvm
  - ssh-copy-id
  - cowsay
  - readline
  - openssl
  - pv
  - pyenv-virtualenv
  - wget
  - wrk
  - zsh
  - zsh-completions

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts
  - domt4/autoupdate
  - sambadevi/powerlevel9k

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - autodmg
  - autopkgr
  - balenaetcher
  - chromedriver
  - cyberduck
  - docker
  - dropbox
  - firefox
  - font-hack-nerd-font
  - google-chrome
  - handbrake
  - iterm2
  - licecap
  - keybase
  - macvim
  - sequel-pro
  - skitch
  - slack
  - sourcetree
  - sublime-text
  - vagrant
  - vagrant-manager
  - vagrant-vmware-utility
  - veracrypt
  - vmware-fusion

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: "jshanley@gmail.com"
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
